CREATE DATABASE salud;
 
USE salud

CREATE TABLE `contributivo` (
  `tipo_ide` char(2) default NULL,
  `numide` varchar(17) default NULL,
  `apellido1` varchar(20) default NULL,
  `apellido2` varchar(30) default NULL,
  `nombre1` varchar(20) default NULL,
  `nombre2` varchar(30) default NULL,
  `fe_nacimiento` varchar(10) default NULL,
  `departamento` char(2) default NULL,
  `municipio` char(3) default NULL,
  `estado` char(2) default NULL,
  `codeps` varchar(6) default NULL,
  KEY `numide` (`numide`),
  KEY `apellido1` (`apellido1`),
  KEY `apellido2` (`apellido2`),
  KEY `nombre1` (`nombre1`),
  KEY `nombre2` (`nombre2`),
  KEY `tipo_ide` (`tipo_ide`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `dgas` (
  `tipo` char(1) default NULL,
  `consereg` varchar(10) default NULL,
  `departamento` char(2) default NULL,
  `municipio` char(3) default NULL,
  `codeps` varchar(6) default NULL,
  `periodoli` varchar(6) default NULL,
  `tipoide` char(2) default NULL,
  `numide` varchar(17) NOT NULL,
  `sexo` char(1) default NULL,
  `fe_nacimiento` varchar(10) default NULL,
  `apellido1` varchar(20) default NULL,
  `apellido2` varchar(30) default NULL,
  `nombre1` varchar(20) default NULL,
  `nombre2` varchar(30) default NULL,
  `zona` char(1) default NULL,
  `fe_afieps` varchar(10) default NULL,
  `dias` varchar(2) default NULL,
  `modalidad` char(2) default NULL,
  `numpago` char(1) default NULL,
  `cambioeps` char(1) default NULL,
  `epstraslado` varchar(6) default NULL,
  `valorupc` varchar(12) default NULL,
  `glosas` char(1) default NULL,
  KEY `apellido1` (`apellido1`),
  KEY `apellido2` (`apellido2`),
  KEY `nombre1` (`nombre1`),
  KEY `nombre2` (`nombre2`),
  KEY `tipoide` (`tipoide`),
  KEY `numide` (`numide`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `idinvalidas` (
  `tipoide` varchar(2) default NULL,
  `numide` varchar(20) default NULL,
  `nombre1` varchar(20) default NULL,
  `nombre2` varchar(30) default NULL,
  `apellido1` varchar(20) default NULL,
  `apellido2` varchar(30) default NULL,
  `fenaci` varchar(10) default NULL,
  `departamento` varchar(2) default NULL,
  `municipio` varchar(3) default NULL,
  `codeps` varchar(6) default NULL,
  KEY `numide` (`numide`),
  KEY `nombre1` (`nombre1`),
  KEY `nombre2` (`nombre2`),
  KEY `apellido1` (`apellido1`),
  KEY `apellido2` (`apellido2`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `regsub` (
  `conse` varchar(8) default NULL,
  `codeps` varchar(6) default NULL,
  `tipocabe` varchar(2) default NULL,
  `identicafabe` varchar(16) default NULL,
  `tipoideafi` varchar(2) default NULL,
  `ideafi` varchar(20) default NULL,
  `apellido1afi` varchar(20) default NULL,
  `apellido2afi` varchar(30) default NULL,
  `nombre1afi` varchar(20) default NULL,
  `nombre2afi` varchar(30) default NULL,
  `fenacimiento` varchar(10) default NULL,
  `sexo` varchar(2) default NULL,
  `tipoafi` varchar(2) default NULL,
  `parentesco` varchar(2) default NULL,
  `grupopobl` varchar(2) default NULL,
  `np` varchar(2) default NULL,
  `ficha` varchar(8) default NULL,
  `conben` varchar(5) default NULL,
  `coddpto` varchar(2) default NULL,
  `codmunicipio` varchar(3) default NULL,
  `area` varchar(2) default NULL,
  `afisistema` varchar(10) default NULL,
  `afiars` varchar(10) default NULL,
  `numcontrato` varchar(9) default NULL,
  `fecontrato` varchar(10) default NULL,
  `tipocontrato` varchar(2) default NULL,
  `grupoet` varchar(2) default NULL,
  `modsub` varchar(2) default NULL,
  `orden` varchar(2) default NULL,
  `nucleo` varchar(2) default NULL,
  `hogar` varchar(2) default NULL,
  `marcacon` varchar(5) default NULL,
  `discapacidad` varchar(2) default NULL,
  `pagrope` varchar(2) default NULL,
  `posocupa` varchar(2) default NULL,
  `codbarrio` varchar(4) default NULL,
  `estrato` varchar(2) default NULL,
  `puntaje` varchar(5) default NULL,
  `direccion` varchar(50) default NULL,
  `numcar` varchar(10) default NULL,
  `fcarne` varchar(8) default NULL,
  `mescarne` varchar(10) default NULL,
  `entrega` varchar(2) default NULL,
  `estrasoc` varchar(2) default NULL,
  `lotero` varchar(10) default NULL,
  `edad` varchar(4) default NULL,
  `fechahoy` varchar(10) default NULL,
  `acuerdo` varchar(5) default NULL,
  `fechanove` varchar(10) default NULL,
  `novedades` varchar(3) default NULL,
  `nomeps` varchar(30) default NULL,
  `municipio` varchar(30) default NULL,
  `cruce` varchar(2) default NULL,
  `codepsa` varchar(6) default NULL,
  `acuerdoa` varchar(5) default NULL,
  `tipodocben` varchar(2) default NULL,
  `identiben` varchar(16) default NULL,
  `traslado` varchar(6) default NULL,
  `cantidad` varchar(6) default NULL,
  `consecon` varchar(5) default NULL,
  `novedad` varchar(3) default NULL,
  `estado` varchar(6) default NULL,
  `observacion` varchar(180) default NULL,
  `nombre` varchar(50) default NULL,
  `marca` varchar(5) default NULL,
  `marcan` varchar(5) default NULL,
  `relcab` varchar(5) default NULL,
  `contratoa` varchar(5) default NULL,
  `ensbc` varchar(2) default NULL,
  `ensbn` varchar(2) default NULL,
  `nombar` varchar(30) default NULL,
  `prioridad` varchar(2) default NULL,
  `encontc` varchar(6) default NULL,
  `encontn` varchar(6) default NULL,
  `epscon` varchar(6) default NULL,
  `ciden` varchar(2) default NULL,
  `ca1a2n1n2` varchar(2) default NULL,
  `ca1a2n1` varchar(2) default NULL,
  `ca12n1fe` varchar(2) default NULL,
  `inconsiste` varchar(10) default NULL,
  `dupli` varchar(2) default NULL,
  `listadocen` varchar(2) default NULL,
  `muerto` varchar(2) default NULL,
  `encafe` varchar(2) default NULL,
  `encoosn` varchar(2) default NULL,
  `encoosc` varchar(2) default NULL,
  `enindi` varchar(2) default NULL,
  `valido` varchar(2) default NULL,
  `reecoos` varchar(2) default NULL,
  `reecafe` varchar(2) default NULL,
  `enprocc` varchar(2) default NULL,
  `enprocn` varchar(2) default NULL,
  `estadoafil` varchar(2) default NULL,
  `idunica` varchar(16) default NULL,
  KEY `ideafi` (`ideafi`),
  KEY `apellido1afi` (`apellido1afi`),
  KEY `apellido2afi` (`apellido2afi`),
  KEY `nombre1afi` (`nombre1afi`),
  KEY `nombre2afi` (`nombre2afi`),
  KEY `ficha` (`ficha`),
  KEY `tipoideafi` (`tipoideafi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `regsubvalido` (
  `conseafi` varchar(8) default NULL,
  `codeps` varchar(6) default NULL,
  `idecabefami` varchar(2) default NULL,
  `numidecabefami` varchar(16) default NULL,
  `tipoideafi` varchar(2) default NULL,
  `ideafi` varchar(16) default NULL,
  `apellido1` varchar(20) default NULL,
  `apellido2` varchar(30) default NULL,
  `nombre1` varchar(20) default NULL,
  `nombre2` varchar(30) default NULL,
  `fenacimiento` varchar(10) default NULL,
  `sexo` char(1) default NULL,
  `tipoafi` char(1) default NULL,
  `parentesco` varchar(2) default NULL,
  `grupopobla` char(2) default NULL,
  `nivelsisben` char(1) default NULL,
  `numficha` varchar(8) default NULL,
  `condicion` char(1) default NULL,
  `departamento` char(2) default NULL,
  `municipio` char(3) default NULL,
  `zona` char(1) default NULL,
  `feafiliacion` varchar(10) default NULL,
  `feeps` varchar(10) default NULL,
  `numcontra` varchar(9) default NULL,
  `iniciocontra` varchar(10) default NULL,
  `tipo` char(2) default NULL,
  `pertenencia` varchar(2) default NULL,
  `modalidad` char(2) default NULL,
  `estado` char(2) default NULL,
  KEY `ideafi` (`ideafi`),
  KEY `apellido1` (`apellido1`),
  KEY `apellido2` (`apellido2`),
  KEY `nombre1` (`nombre1`),
  KEY `nombre2` (`nombre2`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `sisben` (
  `nuficha` varchar(11) default NULL,
  `region` varchar(11) default NULL,
  `departamento` varchar(11) default NULL,
  `municipio` varchar(11) default NULL,
  `zona` varchar(11) default NULL,
  `tamano` varchar(11) default NULL,
  `sector` varchar(11) default NULL,
  `seccion` varchar(11) default NULL,
  `manzana` varchar(2) default NULL,
  `comuna` varchar(11) default NULL,
  `barrio` varchar(11) default NULL,
  `direccion` varchar(80) default NULL,
  `teles` varchar(10) default NULL,
  `vivienda` varchar(11) default NULL,
  `riesgo` varchar(11) default NULL,
  `pared` varchar(11) default NULL,
  `piso` varchar(11) default NULL,
  `energia` varchar(11) default NULL,
  `alcanta` varchar(11) default NULL,
  `gas` varchar(11) default NULL,
  `telefono` varchar(11) default NULL,
  `basura` varchar(11) default NULL,
  `acueduc` varchar(11) default NULL,
  `estrato` varchar(11) default NULL,
  `agua` varchar(11) default NULL,
  `thogar` varchar(11) default NULL,
  `recolect` varchar(11) default NULL,
  `aplica` varchar(11) default NULL,
  `entidad` varchar(30) default NULL,
  `encuesta` varchar(3) default NULL,
  `supervi` varchar(3) default NULL,
  `digita` varchar(3) default NULL,
  `fecha` varchar(10) default NULL,
  `hogar` varchar(11) default NULL,
  `teneviv` varchar(11) default NULL,
  `tcuartos` varchar(11) default NULL,
  `tdormir` varchar(11) default NULL,
  `sanitar` varchar(11) default NULL,
  `usanitar` varchar(11) default NULL,
  `usosani` varchar(11) default NULL,
  `tsanitar` varchar(11) default NULL,
  `ducha` varchar(11) default NULL,
  `cocinan` varchar(11) default NULL,
  `alumbra` varchar(11) default NULL,
  `usotele` varchar(11) default NULL,
  `nevera` varchar(11) default NULL,
  `lavadora` varchar(11) default NULL,
  `tvcolor` varchar(11) default NULL,
  `tvcable` varchar(11) default NULL,
  `calenta` varchar(11) default NULL,
  `horno` varchar(11) default NULL,
  `aire` varchar(11) default NULL,
  `tpersona` varchar(11) default NULL,
  `orden` varchar(11) default NULL,
  `apellido1` varchar(20) default NULL,
  `apellido2` varchar(20) default NULL,
  `nombre1` varchar(20) default NULL,
  `nombre2` varchar(20) default NULL,
  `parentesco` varchar(11) default NULL,
  `estcivil` varchar(11) default NULL,
  `conyuvive` varchar(11) default NULL,
  `hijosde` varchar(11) default NULL,
  `tipodoc` varchar(11) default NULL,
  `cedula` varchar(20) default NULL,
  `fe_nacimiento` varchar(10) default NULL,
  `sexo` varchar(11) default NULL,
  `embarazada` varchar(11) default NULL,
  `discapacida` varchar(11) default NULL,
  `carnet` varchar(11) default NULL,
  `asiste` varchar(11) default NULL,
  `tipoesta` varchar(11) default NULL,
  `grado` varchar(11) default NULL,
  `nivel` varchar(11) default NULL,
  `activi` varchar(11) default NULL,
  `buscando` varchar(6) default NULL,
  `ingresos` varchar(20) default NULL,
  `edad` varchar(11) default NULL,
  `puntaje` varchar(20) default NULL,
  `fe_afilia` varchar(10) default NULL,
  `nucleo` varchar(3) default NULL,
  `nparentes` varchar(11) default NULL,
  `nivsisben` varchar(11) default NULL,
  `edadact` varchar(11) default NULL,
  KEY `cedula` (`cedula`),
  KEY `apellido1` (`apellido1`),
  KEY `apellido2` (`apellido2`),
  KEY `nombre1` (`nombre1`),
  KEY `nombre2` (`nombre2`),
  KEY `nuficha` (`nuficha`),
  KEY `tipodoc` (`tipodoc`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;